package view;

import controller.OrderController;
import controller.TableController;
import model.ArticleType;
import model.StoreModel;

import javax.swing.*;
import java.util.List;

public class PlaceOrderView extends javax.swing.JFrame {
    private StoreModel store;

    /**
     * Creates new form PlaceOrderView
     */
    public PlaceOrderView(StoreModel store) {
        this.store = store;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        storeLabel = new javax.swing.JLabel();
        storeTextField = new javax.swing.JTextField();
        orderCodeLabel = new javax.swing.JLabel();
        orderCodeTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dateTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        articleTypeTable = new javax.swing.JTable();
        orderButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Place order");

        storeLabel.setText("Store:");

        storeTextField.setEditable(false);
        storeTextField.setText(store.getName());
        storeTextField.setBorder(null);

        orderCodeLabel.setText("Order code:");

        jLabel1.setText("Date:");

        articleTypeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Article type", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(articleTypeTable);

        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orderCodeLabel)
                            .addComponent(storeLabel)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(storeTextField)
                            .addComponent(orderCodeTextField)
                            .addComponent(dateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addComponent(orderButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(storeLabel)
                    .addComponent(storeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderCodeLabel)
                    .addComponent(orderCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orderButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        final int ARTICLE_TYPE_COLUMN = 0;
        final int AMOUNT_COLUMN = 1;

        String[] articleTypesNames = TableController.fetchColumnsFromTable(articleTypeTable, ARTICLE_TYPE_COLUMN);
        String[] amounts = TableController.fetchColumnsFromTable(articleTypeTable, AMOUNT_COLUMN);

        if (articleTypesNames == null || amounts == null) {
            return;
        }

        boolean areArticleTypesStored = areArticleTypesStored(articleTypesNames);

        if (!areArticleTypesStored) {
            JOptionPane.showMessageDialog(this,
                    "Some article type isn't in the database",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);

            return;
        }

        String orderCode = orderCodeTextField.getText();
        String date = dateTextField.getText();
        OrderController.addOrder(orderCode, date, store, articleTypesNames, amounts);
    }//GEN-LAST:event_orderButtonActionPerformed

    private boolean areArticleTypesStored(String[] articleTypes) {
        int matches = 0;
        List<ArticleType> articleTypeList = ArticleType.findAll();

        for (ArticleType articleType : articleTypeList) {
            for (String articleCode : articleTypes) {
                if (articleType.getName().equals(articleCode)) {
                    matches++;
                }
            }
        }

        return (matches - articleTypes.length) == 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new PlaceOrderView(
                new StoreModel("NEG001",
                        "Decathlon",
                        "Via Monte Cristallo",
                        "San Giovanni Lupatoto")).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable articleTypeTable;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel orderCodeLabel;
    private javax.swing.JTextField orderCodeTextField;
    private javax.swing.JLabel storeLabel;
    private javax.swing.JTextField storeTextField;
    // End of variables declaration//GEN-END:variables
}
