package view;

import model.UserModel;

import javax.swing.*;

public class SecretaryView extends javax.swing.JFrame {
    private UserModel user;

    /**
     * Creates new form SecretaryView
     */
    public SecretaryView(UserModel user) {
        this.user = user;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loggedAsLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        insertArticleTypeButton = new javax.swing.JButton();
        ordersFulfillmentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Secretary");

        loggedAsLabel.setText("Logged as:");

        emailTextField.setEditable(false);
        emailTextField.setText(user.getEmail());
        emailTextField.setBorder(null);

        insertArticleTypeButton.setText("Insert article type");
        insertArticleTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertArticleTypeButtonActionPerformed(evt);
            }
        });

        ordersFulfillmentButton.setText("Orders fulfillment");
        ordersFulfillmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersFulfillmentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loggedAsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(insertArticleTypeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ordersFulfillmentButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loggedAsLabel)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(insertArticleTypeButton)
                .addGap(18, 18, 18)
                .addComponent(ordersFulfillmentButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void insertArticleTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertArticleTypeButtonActionPerformed
        SwingUtilities.invokeLater(() -> new InsertArticleTypeView().setVisible(true));
    }//GEN-LAST:event_insertArticleTypeButtonActionPerformed

    private void ordersFulfillmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersFulfillmentButtonActionPerformed
        SwingUtilities.invokeLater(() -> new OrdersFulfillmentView().setVisible(true));
    }//GEN-LAST:event_ordersFulfillmentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new SecretaryView(
                new UserModel("mario.rossi@gmail.com", "Segreteria", null)).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailTextField;
    private javax.swing.JButton insertArticleTypeButton;
    private javax.swing.JLabel loggedAsLabel;
    private javax.swing.JButton ordersFulfillmentButton;
    // End of variables declaration//GEN-END:variables
}
